openapi: 3.0.0
info:
  title: API de Clientes
  version: '1.0'
  description: API para gestionar clientes

paths:
  /clientes:
    get:
      summary: Obtener lista de clientes
      description: Retorna la lista de todos los clientes
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
        httpMethod: POST
        type: aws_proxy
        passthroughBehavior: when_no_match
        timeoutInMillis: 29000
      responses:
        '200':
          description: Lista de clientes obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nombre:
                      type: string
                    email:
                      type: string
        '500':
          description: Error interno del servidor

  /clientes/{id}:
    get:
      summary: Obtener cliente por ID
      description: Retorna los datos de un cliente específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID del cliente a buscar
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${getClienteByIdArn}/invocations"
        httpMethod: POST
        type: aws_proxy
        passthroughBehavior: when_no_match
        timeoutInMillis: 29000
      responses:
        '200':
          description: Cliente encontrado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  nombre:
                    type: string
                  email:
                    type: string
        '404':
          description: Cliente no encontrado
        '400':
          description: ID de cliente no proporcionado
        '500':
          description: Error interno del servidor

# components:
#   securitySchemes:
#     api_key:
#       type: apiKey
#       name: x-api-key
#       in: header
