openapi: 3.0.0
info:
  title: API de Clientes
  version: '1.0'
  description: API para gestionar clientes

paths:
  /clientes:
    get:
      summary: Obtener lista de clientes
      description: Retorna la lista de todos los clientes
      x-amazon-apigateway-integration:
        uri: "arn:aws:apigateway:${region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
        httpMethod: POST
        type: aws_proxy
        passthroughBehavior: when_no_match
        timeoutInMillis: 29000
      responses:
        '200':
          description: Lista de clientes obtenida exitosamente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nombre:
                      type: string
                    email:
                      type: string
        '500':
          description: Error interno del servidor

# components:
#   securitySchemes:
#     api_key:
#       type: apiKey
#       name: x-api-key
#       in: header
