name: Deploy Infrastructure and Lambda Functions

on:
  push:
    paths:
      - 'terraform/**'
      - 'functions/**'
      - 'package.json'

  workflow_dispatch:
      
jobs:
  build-lambdas:
    name: Build Lambda Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install
          yarn global add esbuild
          echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Build Lambda functions
        run: yarn build:all

      - name: Upload Lambda artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lambda-builds
          path: build/*.zip

  terraform-deploy:
    name: Terraform Deploy
    needs: build-lambdas
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download Lambda builds
        uses: actions/download-artifact@v4
        with:
          name: lambda-builds
          path: build

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.0

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=g1-terraform-state-utec" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=g1-terraform-state-lock"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
